FROM golang:1.23 AS build-stage

WORKDIR /app
RUN mkdir /md

RUN go install github.com/go-bindata/go-bindata/v3/go-bindata@latest

COPY go.mod go.sum ./
RUN go mod download

ARG CURRENT_TIME
RUN echo "\necho \"hello: ${CURRENT_TIME}\"" >>  /etc/bash.bashrc 


# RUN make run

# RUN CGO_ENABLED=0 GOOS=linux go build -o /markdown-blog


# # Run the tests in the container
# FROM build-stage AS run-test-stage
# RUN go test -v ./...

# # Deploy the application binary into a lean image
# FROM gcr.io/distroless/base-debian11 AS build-release-stage

# WORKDIR /

# COPY --from=build-stage /docker-gs-ping /docker-gs-ping

# EXPOSE 8080

# USER nonroot:nonroot

# ENTRYPOINT ["/docker-gs-ping"]



EXPOSE 5006

# CMD ["/markdown-blog web"]
