# go的编译镜像

FROM golang:1.23 AS build-stage

EXPOSE 5006
WORKDIR /app
RUN mkdir /md

RUN go install github.com/go-bindata/go-bindata/v3/go-bindata@latest

COPY go.mod go.sum ./
RUN go mod download


ARG CURRENT_TIME
RUN echo "\necho \"hello: ${CURRENT_TIME}\"" >>  /etc/bash.bashrc 
